spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=com.linkfit.admin.domain
mybatis.configuration.map-underscore-to-camel-case=true

logging.level.root=WARN
logging.level.com.linkfit.admin=INFO
